name: auth
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  razorpay_flutter: ^1.3.7 # Add Razorpay Flutter SDK

  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.9
  flutter_tflite: ^1.0.1
  shared_preferences: ^2.2.0
  mongo_dart: ^0.9.2
  http: ^1.1.0
  badges: ^3.1.2
  provider: ^6.1.2
  intl: ^0.19.0
  fl_chart: ^0.70.2 # Add this line
  google_fonts: ^6.2.1
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:

    - assets/myModel2.tflite
    - assets/labels.txt
    - assets/upload.jpg
    - assets/fruit.txt
    - assets/fruit_recognizer.tflite
    - .env
    - assets/fruit_Condition_detection_90.tflite
    - assets/fruit_Condition_detection_epoch_91.tflite
    - assets/fruit_condition.txt
    - assets/disease.txt
    - assets/1.tflite
    - assets/2.tflite
